fp32-training:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-generative-ai-stable-diffusion-training
  cmd: bash run_model.sh
  cap_add: 'SYS_NICE'
  env:
    PRECISION: fp32
    OUTPUT_DIR: /tmp
    NNODES: '1'
    DISTRIBUTED: 'true'
    TORCH_INDUCTOR: '0'
    DATASET_DIR: /localdisk/pytorch/sd-train
    HOSTFILE: /localdisk/hostfile
  volumes:
    - src: /tmp
      dst: /tmp
    - src: /localdisk/pytorch/sd-train
      dst: /localdisk/pytorch/sd-train
    - src: /localdisk/hostfile
      dst: /localdisk/hostfile
bf16-training:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-generative-ai-stable-diffusion-training
  cmd: bash run_model.sh
  cap_add: 'SYS_NICE'
  env:
    PRECISION: bf16
    OUTPUT_DIR: /tmp
    NNODES: '1'
    DISTRIBUTED: 'true'
    TORCH_INDUCTOR: '0'
    DATASET_DIR: /localdisk/pytorch/sd-train
    HOSTFILE: /localdisk/hostfile
  volumes:
    - src: /tmp
      dst: /tmp
    - src: /localdisk/pytorch/sd-train
      dst: /localdisk/pytorch/sd-train
    - src: /localdisk/hostfile
      dst: /localdisk/hostfile
fp16-training:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-generative-ai-stable-diffusion-training
  cmd: bash run_model.sh
  cap_add: 'SYS_NICE'
  env:
    PRECISION: fp16
    OUTPUT_DIR: /tmp
    NNODES: '1'
    DISTRIBUTED: 'true'
    TORCH_INDUCTOR: '0'
    DATASET_DIR: /localdisk/pytorch/sd-train
    HOSTFILE: /localdisk/hostfile
    DNNL_MAX_CPU_ISA: AVX512_CORE_AMX_FP16
  volumes:
    - src: /tmp
      dst: /tmp
    - src: /localdisk/pytorch/sd-train
      dst: /localdisk/pytorch/sd-train
    - src: /localdisk/hostfile
      dst: /localdisk/hostfile
bf32-training:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-generative-ai-stable-diffusion-training
  cmd: bash run_model.sh
  cap_add: 'SYS_NICE'
  env:
    PRECISION: bf32
    OUTPUT_DIR: /tmp
    NNODES: '1'
    DISTRIBUTED: 'true'
    TORCH_INDUCTOR: '0'
    DATASET_DIR: /localdisk/pytorch/sd-train
    HOSTFILE: /localdisk/hostfile
  volumes:
    - src: /tmp
      dst: /tmp
    - src: /localdisk/pytorch/sd-train
      dst: /localdisk/pytorch/sd-train
    - src: /localdisk/hostfile
      dst: /localdisk/hostfile
