fp32-throughput-inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-generative-ai-stable-diffusion-inference
  cmd: bash run_model.sh
  cap_add: 'SYS_NICE'
  env:
    PRECISION: fp32
    OUTPUT_DIR: /tmp
    MODE: ipex-jit
    TEST_MODE: 'THROUGHPUT'
    TORCH_INDUCTOR: '0'
    DISTRIBUTED: 'False'
    DATASET_DIR: /pytorch/coco/coco
  volumes:
    - src: /tmp
      dst: /tmp
    - src: /pytorch/coco/coco
      dst: /pytorch/coco/coco
bf32-throughput-inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-generative-ai-stable-diffusion-inference
  cmd: bash run_model.sh
  cap_add: 'SYS_NICE'
  env:
    PRECISION: bf32
    OUTPUT_DIR: /tmp
    MODE: ipex-jit
    TEST_MODE: 'THROUGHPUT'
    TORCH_INDUCTOR: '0'
    DISTRIBUTED: 'False'
    DATASET_DIR: /pytorch/coco/coco
  volumes:
    - src: /tmp
      dst: /tmp
    - src: /pytorch/coco/coco
      dst: /pytorch/coco/coco
bf16-throughput-inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-generative-ai-stable-diffusion-inference
  cmd: bash run_model.sh
  cap_add: 'SYS_NICE'
  env:
    PRECISION: bf16
    OUTPUT_DIR: /tmp
    MODE: ipex-jit
    TEST_MODE: 'THROUGHPUT'
    TORCH_INDUCTOR: '0'
    DISTRIBUTED: 'False'
    DATASET_DIR: /pytorch/coco/coco
  volumes:
    - src: /tmp
      dst: /tmp
    - src: /pytorch/coco/coco
      dst: /pytorch/coco/coco
fp16-throughput-inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-generative-ai-stable-diffusion-inference
  cmd: bash run_model.sh
  cap_add: 'SYS_NICE'
  env:
    PRECISION: fp16
    OUTPUT_DIR: /tmp
    MODE: ipex-jit
    TEST_MODE: 'THROUGHPUT'
    TORCH_INDUCTOR: '0'
    DISTRIBUTED: 'False'
    DATASET_DIR: /pytorch/coco/coco
    DNNL_MAX_CPU_ISA: AVX512_CORE_AMX_FP16
  volumes:
    - src: /tmp
      dst: /tmp
    - src: /pytorch/coco/coco
      dst: /pytorch/coco/coco
int8-fp32-throughput-inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-generative-ai-stable-diffusion-inference
  cmd: bash run_model.sh
  cap_add: 'SYS_NICE'
  env:
    PRECISION: int8-fp32
    OUTPUT_DIR: /tmp
    MODE: ipex-jit
    TEST_MODE: 'THROUGHPUT'
    TORCH_INDUCTOR: '0'
    DISTRIBUTED: 'False'
    DATASET_DIR: /pytorch/coco/coco
    INT8_MODEL: /pytorch/sd/models/int8/sd_v2_1.pt
  volumes:
    - src: /tmp
      dst: /tmp
    - src: /pytorch/coco/coco
      dst: /pytorch/coco/coco
    - src: /pytorch/sd/models/int8/sd_v2_1.pt
      dst: /pytorch/sd/models/int8/sd_v2_1.pt
int8-bf16-throughput-inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-generative-ai-stable-diffusion-inference
  cmd: bash run_model.sh
  cap_add: 'SYS_NICE'
  env:
    PRECISION: int8-bf16
    OUTPUT_DIR: /tmp
    MODE: ipex-jit
    TEST_MODE: 'THROUGHPUT'
    TORCH_INDUCTOR: '0'
    DISTRIBUTED: 'False'
    DATASET_DIR: /pytorch/coco/coco
    INT8_MODEL: /pytorch/sd/models/int8/sd_v2_1.pt
  volumes:
    - src: /tmp
      dst: /tmp
    - src: /pytorch/coco/coco
      dst: /pytorch/coco/coco
    - src: /pytorch/sd/models/int8/sd_v2_1.pt
      dst: /pytorch/sd/models/int8/sd_v2_1.pt
fp32-realtime-inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-generative-ai-stable-diffusion-inference
  cmd: bash run_model.sh
  cap_add: 'SYS_NICE'
  env:
    PRECISION: fp32
    OUTPUT_DIR: /tmp
    MODE: ipex-jit
    TEST_MODE: 'REALTIME'
    TORCH_INDUCTOR: '0'
    DISTRIBUTED: 'False'
    DATASET_DIR: /pytorch/coco/coco
  volumes:
    - src: /tmp
      dst: /tmp
    - src: /pytorch/coco/coco
      dst: /pytorch/coco/coco
bf32-realtime-inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-generative-ai-stable-diffusion-inference
  cmd: bash run_model.sh
  cap_add: 'SYS_NICE'
  env:
    PRECISION: bf32
    OUTPUT_DIR: /tmp
    MODE: ipex-jit
    TEST_MODE: 'REALTIME'
    TORCH_INDUCTOR: '0'
    DISTRIBUTED: 'False'
    DATASET_DIR: /pytorch/coco/coco
  volumes:
    - src: /tmp
      dst: /tmp
    - src: /pytorch/coco/coco
      dst: /pytorch/coco/coco
bf16-realtime-inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-generative-ai-stable-diffusion-inference
  cmd: bash run_model.sh
  cap_add: 'SYS_NICE'
  env:
    PRECISION: bf16
    OUTPUT_DIR: /tmp
    MODE: ipex-jit
    TEST_MODE: 'REALTIME'
    TORCH_INDUCTOR: '0'
    DISTRIBUTED: 'False'
    DATASET_DIR: /pytorch/coco/coco
  volumes:
    - src: /tmp
      dst: /tmp
    - src: /pytorch/coco/coco
      dst: /pytorch/coco/coco
fp16-realtime-inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-generative-ai-stable-diffusion-inference
  cmd: bash run_model.sh
  cap_add: 'SYS_NICE'
  env:
    PRECISION: fp16
    OUTPUT_DIR: /tmp
    MODE: ipex-jit
    TEST_MODE: 'REALTIME'
    TORCH_INDUCTOR: '0'
    DISTRIBUTED: 'False'
    DATASET_DIR: /pytorch/coco/coco
    DNNL_MAX_CPU_ISA: AVX512_CORE_AMX_FP16
  volumes:
    - src: /tmp
      dst: /tmp
    - src: /pytorch/coco/coco
      dst: /pytorch/coco/coco
int8-fp32-realtime-inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-generative-ai-stable-diffusion-inference
  cmd: bash run_model.sh
  cap_add: 'SYS_NICE'
  env:
    PRECISION: int8-fp32
    OUTPUT_DIR: /tmp
    MODE: ipex-jit
    TEST_MODE: 'REALTIME'
    TORCH_INDUCTOR: '0'
    DISTRIBUTED: 'False'
    DATASET_DIR: /pytorch/coco/coco
    INT8_MODEL: /pytorch/sd/models/int8/sd_v2_1.pt
  volumes:
    - src: /tmp
      dst: /tmp
    - src: /pytorch/coco/coco
      dst: /pytorch/coco/coco
    - src: /pytorch/sd/models/int8/sd_v2_1.pt
      dst: /pytorch/sd/models/int8/sd_v2_1.pt
int8-bf16-realtime-inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-generative-ai-stable-diffusion-inference
  cmd: bash run_model.sh
  cap_add: 'SYS_NICE'
  env:
    PRECISION: int8-bf16
    OUTPUT_DIR: /tmp
    MODE: ipex-jit
    TEST_MODE: 'REALTIME'
    TORCH_INDUCTOR: '0'
    DISTRIBUTED: 'False'
    DATASET_DIR: /pytorch/coco/coco
    INT8_MODEL: /pytorch/sd/models/int8/sd_v2_1.pt
  volumes:
    - src: /tmp
      dst: /tmp
    - src: /pytorch/coco/coco
      dst: /pytorch/coco/coco
    - src: /pytorch/sd/models/int8/sd_v2_1.pt
      dst: /pytorch/sd/models/int8/sd_v2_1.pt
fp32-accuracy-inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-generative-ai-stable-diffusion-inference
  cmd: bash run_model.sh
  cap_add: 'SYS_NICE'
  env:
    PRECISION: fp32
    OUTPUT_DIR: /tmp
    MODE: ipex-jit
    TEST_MODE: 'ACCURACY'
    TORCH_INDUCTOR: '0'
    DISTRIBUTED: 'False'
    DATASET_DIR: /pytorch/coco/coco
  volumes:
    - src: /tmp
      dst: /tmp
    - src: /pytorch/coco/coco
      dst: /pytorch/coco/coco
bf32-accuracy-inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-generative-ai-stable-diffusion-inference
  cmd: bash run_model.sh
  cap_add: 'SYS_NICE'
  env:
    PRECISION: bf32
    OUTPUT_DIR: /tmp
    MODE: ipex-jit
    TEST_MODE: 'ACCURACY'
    TORCH_INDUCTOR: '0'
    DISTRIBUTED: 'False'
    DATASET_DIR: /pytorch/coco/coco
  volumes:
    - src: /tmp
      dst: /tmp
    - src: /pytorch/coco/coco
      dst: /pytorch/coco/coco
bf16-accuracy-inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-generative-ai-stable-diffusion-inference
  cmd: bash run_model.sh
  cap_add: 'SYS_NICE'
  env:
    PRECISION: bf16
    OUTPUT_DIR: /tmp
    MODE: ipex-jit
    TEST_MODE: 'ACCURACY'
    TORCH_INDUCTOR: '0'
    DISTRIBUTED: 'False'
    DATASET_DIR: /pytorch/coco/coco
  volumes:
    - src: /tmp
      dst: /tmp
    - src: /pytorch/coco/coco
      dst: /pytorch/coco/coco
fp16-accuracy-inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-generative-ai-stable-diffusion-inference
  cmd: bash run_model.sh
  cap_add: 'SYS_NICE'
  env:
    PRECISION: fp16
    OUTPUT_DIR: /tmp
    MODE: ipex-jit
    TEST_MODE: 'ACCURACY'
    TORCH_INDUCTOR: '0'
    DISTRIBUTED: 'False'
    DATASET_DIR: /pytorch/coco/coco
    DNNL_MAX_CPU_ISA: AVX512_CORE_AMX_FP16
  volumes:
    - src: /tmp
      dst: /tmp
    - src: /pytorch/coco/coco
      dst: /pytorch/coco/coco
int8-fp32-accuracy-inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-generative-ai-stable-diffusion-inference
  cmd: bash run_model.sh
  cap_add: 'SYS_NICE'
  env:
    PRECISION: int8-fp32
    OUTPUT_DIR: /tmp
    MODE: ipex-jit
    TEST_MODE: 'ACCURACY'
    TORCH_INDUCTOR: '0'
    DISTRIBUTED: 'False'
    DATASET_DIR: /pytorch/coco/coco
    INT8_MODEL: /pytorch/sd/models/int8/sd_v2_1.pt
  volumes:
    - src: /tmp
      dst: /tmp
    - src: /pytorch/coco/coco
      dst: /pytorch/coco/coco
    - src: /pytorch/sd/models/int8/sd_v2_1.pt
      dst: /pytorch/sd/models/int8/sd_v2_1.pt
int8-bf16-accuracy-inference:
  img: ${REGISTRY}/aiops/mlops-ci:b-${GITHUB_RUN_NUMBER:-0}-${BASE_IMAGE_NAME:-ubuntu}-${BASE_IMAGE_TAG:-22.04}-generative-ai-stable-diffusion-inference
  cmd: bash run_model.sh
  cap_add: 'SYS_NICE'
  env:
    PRECISION: int8-bf16
    OUTPUT_DIR: /tmp
    MODE: ipex-jit
    TEST_MODE: 'ACCURACY'
    TORCH_INDUCTOR: '0'
    DISTRIBUTED: 'False'
    DATASET_DIR: /pytorch/coco/coco
    INT8_MODEL: /pytorch/sd/models/int8/sd_v2_1.pt
  volumes:
    - src: /tmp
      dst: /tmp
    - src: /pytorch/coco/coco
      dst: /pytorch/coco/coco
    - src: /pytorch/sd/models/int8/sd_v2_1.pt
      dst: /pytorch/sd/models/int8/sd_v2_1.pt
